version: '3.1'

services:
  app-utils:
    restart: always
    container_name: app-utils
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  nginx:
    restart: always
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./utils-dist:/var/www/html/
